// Copyright (C) 2026 Red Hat, Inc. and individual contributors as indicated by the @author tags.
// You may not use this file except in compliance with the Apache License, Version 2.0.

package io.agroal.pool.wrapper.closed;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Sentinel implementation of {@link Statement} that throws {@link SQLException} on all operations.
 *
 * @author <a href="gegastaldi@gmail.com">George Gastaldi</a>
 */
public class ClosedStatement implements Statement {

    public static final ClosedStatement INSTANCE = new ClosedStatement();

    // --- //

    protected ClosedStatement() {
    }

    protected SQLException closed() {
        return new SQLException( "Statement is closed" );
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        throw closed();
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        throw closed();
    }

    @Override
    public void close() {
        // no-op
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        throw closed();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        throw closed();
    }

    @Override
    public int getMaxRows() throws SQLException {
        throw closed();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        throw closed();
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        throw closed();
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        throw closed();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        throw closed();
    }

    @Override
    public void cancel() throws SQLException {
        throw closed();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        throw closed();
    }

    @Override
    public void clearWarnings() throws SQLException {
        throw closed();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        throw closed();
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        throw closed();
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        throw closed();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        throw closed();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        throw closed();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        throw closed();
    }

    @Override
    public int getFetchDirection() throws SQLException {
        throw closed();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        throw closed();
    }

    @Override
    public int getFetchSize() throws SQLException {
        throw closed();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        throw closed();
    }

    @Override
    public int getResultSetType() throws SQLException {
        throw closed();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        throw closed();
    }

    @Override
    public void clearBatch() throws SQLException {
        throw closed();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        throw closed();
    }

    @Override
    public Connection getConnection() throws SQLException {
        throw closed();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        throw closed();
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw closed();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw closed();
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw closed();
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        throw closed();
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        throw closed();
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw closed();
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        throw closed();
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        throw closed();
    }

    @Override
    public boolean isClosed() {
        return true;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        throw closed();
    }

    @Override
    public boolean isPoolable() throws SQLException {
        throw closed();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        throw closed();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        throw closed();
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        throw closed();
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        throw closed();
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        throw closed();
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        throw closed();
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        throw closed();
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw closed();
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw closed();
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        throw closed();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        throw closed();
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        throw closed();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName();
    }
}
